### ISSUE TITLE
LICENCE 问题

### ISSUE THREAD

**Issue by Wybxc** [wyapx/Elaina#1]
mirai 及 mirai-api-http 均使用了 AGPLv3 开源协议，按照 AGPLv3 的要求，开发其他语言 SDK 属于间接接触到 mirai 项目，需要使用同样的开源协议。

目前本项目使用的是 LGPL2.1，建议更换到 AGPLv3，否则属于侵犯版权的行为。

**Comment by wyapx** [comment]
没留意issue，实在抱歉
这个确实是个问题，之前没有研究agpl，以为传染性没那么强来着
